### ISSUE TITLE
API data show on admin panel wordpress

### ISSUE THREAD

**Issue by theumar98** [roanuz/cricket-wordpress#1]
When I add short code on page editor we got two bugs
1. page not update or save (show error : "Updating failed" )
but that page refresh than page auto save
2. after that data show on editor page and view page both sides

**Comment by SaiSudheerRz** [comment]
Which Wordpress version you are using?

**Comment by SaiSudheerRz** [comment]
> When I add short code on page editor we got two bugs
> 
> 1. page not update or save (show error : "Updating failed" )
>    but that page refresh than page auto save
> 2. after that data show on editor page and view page both sides

We haven’t heard back from you in a while, so I’m going to mark this as closed. If you have any further questions, you can start a new thread.
